### PR TITLE
Update GNOME runtime to version 46.

### PR DESCRIPTION
**Pull request by ghost**
GNOME runtime version 44 has reached EOL.

### CODE REVIEW

**Comment by ghost** [comment]
```
{
    "errors": [
        "appstream-missing-developer-name",
        "appstream-failed-validation",
        "desktop-file-failed-validation"
    ],
    "appstream": [
        "E: io.gitlab.gwendalj.package-transporter.desktop:3: cid-rdns-contains-hyphen"
    ],
    "desktopfile": [
        "error: value \"Flatpak;Utility\" for key \"Categories\" in group \"Desktop Entry\" contains an unregistered value \"Flatpak\"; values extending the format should start with \"X-\"",
        "error: file contains key \"Description\" in group \"Desktop Entry\", but keys extending the format should start with \"X-\"\n/tmp/tmp_o7866ey/applications/"
    ],
    "info": [
        "appstream-failed-validation: Metainfo file /tmp/tmp0lg7q5mu/metainfo/io.gitlab.gwendalj.package-transporter.metainfo.xml has failed validation. Please see the errors in appstream block",
        "appstream-missing-developer-name: No developer tag found in Metainfo file",
        "desktop-file-failed-validation: Desktop file: io.gitlab.gwendalj.package-transporter.desktop has failed validation. Please see the errors in desktopfile block"
    ],
    "message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
```

**Comment by ghost** [comment]
Ekran Görüntüsü 2024-11-11 16-57-48

**Comment by ghost** [comment]
The application is freezing and not responding.

**Comment by ghost** [comment]
@knacky34 GNOME runtime version 44 has reached EOL.

I tried using runtime version 46 for the package transporter, but it is freezing. Could you try to use a newer version of the runtime? 
Thanks.

**Comment by knacky34** [comment]
@yakushabb,
I stopped developing the application. I will not fix this issue in the near future.
Sorry for the inconvenience

**EDIT:**
Actually, I tried to fix the issue. When updating to Gnome platform 47, GI does not find namespace AppStreamGlib which app depends on. Has it been removed?

**Comment by ghost** [comment]
I'm very late to answer. Yes, it is replaced with AppStream.

**Pull request closed without merging**
